//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursova
{
    using System;
    using System.Collections.Generic;
    
    public partial class documents_data
    {
        public string title { get; set; }
        public int id_document { get; set; }
    
        public virtual Documents Documents { get; set; }
    }
}
