//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursova
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests_documents
    {
        public int id { get; set; }
        public int id_clients { get; set; }
        public int id_servises { get; set; }
        public int id_document { get; set; }
        public System.DateTime data { get; set; }
        public byte[] status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Documents Documents { get; set; }
        public virtual Services Services { get; set; }
    }
}
